################################################
#  ██████╗██████╗ ██╗   ██╗██╗     ██╗ █████╗  #
# ██╔════╝██╔══██╗╚██╗ ██╔╝██║     ██║██╔══██╗ #
# ██║     ██████╔╝ ╚████╔╝ ██║     ██║███████║ #
# ██║     ██╔══██╗  ╚██╔╝  ██║     ██║██╔══██║ #
# ╚██████╗██║  ██║   ██║   ███████╗██║██║  ██║ #
#  ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝╚═╝  ╚═╝ #
################################################

# Set the window Width and Height in console columns.
# The window size will change if the font size changes.
window:
  dimensions:
    columns: 110
    lines: 30
  decorations: full
  startup_mode: Windowed
  title: "Alacritty Terminal"
  dynamic_title: true
# Scrolling history and multiplier
scrolling:
  history: 10000
  multiplier: 3
# Font family and style
font:
  normal:
    family: "Hack Nerd Font"
    style: Regular
  bold:
    family: "Hack Nerd Font"
    style: Bold
  italic:
    family: "SourceCodePro"
    style: italic
  bold_italic:
    family: "SourceCodePro"
    style: Bold Italic
  size: 10.0
  offset:
    x: 0
    y: 0
  draw_bold_text_with_bright_colors: false
# Background opacity from 0.0 transparent, 1.0 Opaque
window:
  opacity: 0.8
# Terminal colors
colors:
  primary:
    background: '#000000'
    foreground: '#FFFFFF'
  cursor:
    cursor: '#00b8ff'
  search:
    matches:
      foreground: '#000000'
      background: '#EA80FC'
    focus_match:
      foreground: '#000000'
      background: '#E040FB'
    color.footer_bar:
      foreground: '#B388FF'
      background: '#121212'
  selection:
    text: '#EA80FC'
    background: '#121212'
  normal:
    black: '#121212'
    red: '#ff5252'
    green: '#8BC34A'
    yellow: '#FFFF00'
    blue: '#82B1FF'
    magenta: '#EA80FC'
    cyan: '#84FFFF'
    white: '#FFFFFF'
  bright:
    black: '#363636'
    red: '#ef9a9a'
    green: '#A5D6A7'
    yellow: '#FFF59D'
    blue: '#90CAF9'
    magenta: '#CE93D8'
    cyan: '#80DEEA'
    white: '#FFFFFF'
# Cursor styling
cursor:
  style: Beam
  thickness: 0.2
  unfocused_hollow: false
  blink_interval: 750

################################################################################
# ███████╗██╗  ██╗ ██████╗ ██████╗ ████████╗ ██████╗██╗   ██╗████████╗███████╗ #
# ██╔════╝██║  ██║██╔═══██╗██╔══██╗╚══██╔══╝██╔════╝██║   ██║╚══██╔══╝██╔════╝ #
# ███████╗███████║██║   ██║██████╔╝   ██║   ██║     ██║   ██║   ██║   ███████╗ #
# ╚════██║██╔══██║██║   ██║██╔══██╗   ██║   ██║     ██║   ██║   ██║   ╚════██║ #
# ███████║██║  ██║╚██████╔╝██║  ██║   ██║   ╚██████╗╚██████╔╝   ██║   ███████║ #
# ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═════╝    ╚═╝   ╚══════╝ #
################################################################################                                                                            

# Mouse
mouse_bindings:
 - { mouse: Right, action: Paste }

# Keyboard
key_bindings:
 - { key: C, mods: Control|Shift, action: Copy }
 - { key: V, mods: Control|Shift, action: Paste }
 - { key: C, mods: Control, mode: Vi, action: ClearSelection }
